# Generated by Django 5.2.6 on 2025-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_content_message_message_message_handled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='handled',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
